### ISSUE TITLE
活跃度指标设计v2

### ISSUE THREAD

**Issue by seeflood** [seeflood/github-growth-hack#2]
## 1. 设计目标
在v1版本基础上增加负反馈，以便激励各个项目：
- 即时回复社区提的issue
- 即时回复社区提的PR

消灭0回复!

## 2. 指标设计：方案A,扣分制
![image](https://user-images.githubusercontent.com/26001097/148624794-129025ba-6e05-4cef-a738-b9ee1dd90e88.png)

### 计算规则
如果issue回帖人里没有member，也算0回复；
如果issue发帖人是member，则不计算在内；
3月11日更新：打了`help wanted`或者`good first issue`的，不计算在内；

### 另一种选择
open digger社区的另一个思路是：分别计算每个贡献者的贡献度（可以理解成计算每个contributor的”得分“），最后项目的总贡献度=每个贡献者贡献度的根号求和。
这种设计的好处是：可以抹平核心贡献者活跃度过高导致的项目整体活跃度较高，而对长尾参与者较为友好

但是v2的设计目标不同，v2的设计目标是”消灭0回复“，不强调社区多元化

#### Pros
1. 只需要一个指标即可搭建奖/惩机制，简单，方便理解
比如可以定一个deadline阈值，长时间低于deadline的项目可以启动破产机制，推动下线/改名

#### Cons
1. 大量项目得分负数，开局分太低，大家缺乏动力投入
因此可以：
a. 可以设计一个统计的时间窗口，比如"只统计从去年6月到现在的issue/pr"
b. 换一种思路，得分太低，说明这个项目应该归档

2. 解决不了”1回复问题“：member回1次issue或者PR，然后提问者补充提问，或者pr贡献者修改pr后，即使member再也不回，指标也不会有负反馈
对于这个问题，考虑在v3解决，v2先解决0回复问题
解决思路: 统计"超过一定期限未关闭的issue/pr数"

## 3. 破产机制
- 长期低于deadline的项目，进入破产重组期
- 破产重组期结束后，仍低于deadline的项目建议 archive，或者改名、移动进其他组织

## 4. 其他优化
- [ ] 目前没把pr review数统计在内，这个也应该算回复，见 #1 
- [ ] 需要对多个项目做”聚合统计“。比如应该把layotto,layotto java sdk,layotto .net sdk等一起统计，计算出"layotto"的总活跃度

## 5. TODO
- [x] 开发工具，跑分看下效果；
- [x] 根据跑分结果，调整加权参数；
- [x] 舆情issue报警
- [ ] 推动机器人：机器人每天@或私聊项目负责人，催促回复
- [ ] Deadline报警
设计一个Deadline，当某个项目达到Deadline，报警建议archive.
literally deadline :)

### 2月12日
统计所有开着的issue里，发帖人不是member、没有member回帖的issue，扣分
![image](https://user-images.githubusercontent.com/26001097/153695369-798d583d-a0e7-4569-b747-21485e4094e7.png)

跑出数据后感觉有点反直觉：怎么做的好的项目，反而比缺少技术人日的项目分数更低？
去检查了下发现确实存在很多长期0回复的issue，比如:
https://github.com/mosn/mosn/issues/1279

这是个好机会，推动重点项目把旧issue清下、保证即时回复新issue

**Comment by seeflood** [comment]
## 上述指标存在的问题
某些项目开局分数太低（都是负数），维护者没动力继续投入了

## 方案b
![image](https://user-images.githubusercontent.com/26001097/149665454-f4830e89-444a-4860-87aa-87734de35237.png)

![image](https://user-images.githubusercontent.com/26001097/149665759-5a4159da-5fa7-4401-a04c-9897dc294a7d.png)

解释：
1. 扣分制改成加分制
2. 缺点是长时间不回的issue权重低，没有回复动力
因此可以另外设计一个“腐败指数”, 统计超过deadline没关闭的issue/pr，达到阈值推动archive

**Comment by seeflood** [comment]
## 运营指标设计
### 流量模型
![image](https://user-images.githubusercontent.com/26001097/149667778-14caf116-396b-43b7-8af9-de603ae9ca52.png)

![image](https://user-images.githubusercontent.com/26001097/149667765-73004c75-f75b-4d5c-8585-6963c2224611.png)

### 指标
1. 仓库uv
2. star转化率
3. contributor转化率

**Comment by seeflood** [comment]
### 2月15更新
讨论决定：
1. 使用扣分制，只统计从2022年1月1之后创建的issue，舆情只看今年的，因为过去清理成本太高。
统计如下：
![image](https://user-images.githubusercontent.com/26001097/154002377-b6d9f3b2-bed1-4775-b112-be31fd62fcd8.png)

2. 加了个功能，生成舆情issue列表，同步到群聊/群发邮件报警
![image](https://user-images.githubusercontent.com/26001097/154002518-750ce62a-33de-41fd-a22b-55a88f3d26b9.png)
![image](https://user-images.githubusercontent.com/26001097/154007425-292b3af8-6021-4c2b-aac7-c44be4b51005.png)

**Comment by seeflood** [comment]
![image](https://user-images.githubusercontent.com/26001097/156515698-ebaf02ab-5ffe-4fb9-9201-a76e44274d3a.png)

**Comment by seeflood** [comment]
![image](https://user-images.githubusercontent.com/26001097/157366957-6fb03357-97e0-47b3-80e5-e8b8c88ad96e.png)
